name: Feature Request
description: Request for a new feature
title: '[Feature]: '
labels: ['feature-request', 'enhancement']
assignees:
  - illusion47586
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: dropdown
    id: where
    attributes:
      label: In which process do you want a new feature?
      description: For features that do not use native features and are more related to Pluto/Julia, please report them to there respective repos.
      options:
        - Software Installation
        - Julia Installation
        - Pluto Installation
        - Opening a file
        - Moving a file
        - Exporting a file
        - Something else
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature / Improvement
      description: You can use images to explain better.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.0.1-alpha
        - 0.0.2-alpha
        - 0.0.2
    validations:
      required: true
