/**
 * Main process of the Electron application.
 */
import { app, BrowserWindow, nativeTheme, session } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
import Pluto from './pluto';
import { initGlobals, startup } from './startup.ts';
import { generalLogger } from './logger.ts';
import { GlobalWindowManager } from './windowHelpers.ts';
import { Globals } from './globals.ts';
import { start } from 'repl';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Get the path to the generated_assets directory
// When packaged: process.resourcesPath points to the resources directory
// When in development: use app.getAppPath() to get the project root
function getAssetsPath(): string {
  if (app.isPackaged) {
    // In production, extraResource files are in process.resourcesPath
    return path.join(process.resourcesPath, 'generated_assets');
  } else {
    // In development, use app.getAppPath() to get the application root
    const appPath = app.getAppPath();
    return path.join(appPath, 'generated_assets');
  }
}

function getAssetPath(...paths: string[]): string {
  return path.join(process.resourcesPath, ...paths);
};

// function readArchitectureFile(): string | null {
//   const assetsPath = getAssetsPath();
//   const archFilePath = path.join(assetsPath, 'architecture.txt');

//   try {
//     if (!fs.existsSync(archFilePath)) {
//       console.warn('architecture.txt not found in generated_assets');
//       return null;
//     }

//     const arch = fs.readFileSync(archFilePath, 'utf8').trim();
//     console.log(`Architecture from generateAssets: ${arch}`);
//     return arch;
//   } catch (error) {
//     console.warn('Failed to read architecture.txt:', error);
//     return null;
//   }
// }

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Methods from old main.ts file below
// Disable GPU Acceleration for Windows 7
// if (release().startsWith('6.1')) app.disableHardwareAcceleration();

// // Set application name for Windows 10+ notifications
// if (process.platform === 'win32') app.setAppUserModelId(app.getName());


// if (!app.requestSingleInstanceLock()) {
//   app.quit();
//   process.exit(0);
// }

// ipcMain.on('ipc-example', async (event, args) => {
//   const msgTemplate = (pingPong: string) => `IPC test: ${pingPong}`;
//   console.log(msgTemplate(args));
//   event.reply('ipc-example', msgTemplate('pong'));
// });

/**
 * - A function to create a pluto window.
 * - It checks whether called from CLI or GUI.
 * - It checks if a pluto instance is already running.
 * - Installs dev extensions if needed
 * - Takes care of app updates
 *
 * *NOTE:* If any param is `unknown` it is overwritten by the CLI options,
 * if possible.
 *
 * @param url the URL to open in this window
 * @param project the project folder location
 * @param notebook the path to a pluto notebook
 * @returns nothing
 */
const createWindow = (): void => {
  // Determine preload script path
  let preloadPath: string | undefined;
  
  if (fs.existsSync(MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY)) {
    preloadPath = MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY;
  } else {
    // In development, try the .webpack directory directly
    const devPreloadPath = path.join(app.getAppPath(), '.webpack/renderer/main_window/preload.js');
    if (fs.existsSync(devPreloadPath)) {
      preloadPath = devPreloadPath;
    }
  }

  const win = new BrowserWindow({
      title: '⚡ Pluto ⚡',
      height: 800,
      width: 700,
      resizable: true,
      show: true,
      backgroundColor: nativeTheme.shouldUseDarkColors ? '#1F1F1F' : 'white',
      icon: getAssetPath('icon.png'),
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      },
    });
    
    const firstPluto = new Pluto(win);
    // const window = firstPluto.getBrowserWindow();
    win.focus();

    win.webContents.setVisualZoomLevelLimits(1, 3);
    win.setMenuBarVisibility(false);  
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(async () => {
// app.on('ready', async () => {

// Read the architecture file generated by generateAssets
  // const arch = readArchitectureFile();
  // if (arch) {
  //   console.log(`Running on architecture: ${arch}`);
  // }
  await initGlobals();
  createWindow();
  startup(app);

  // This is set here because it required the app to be ready
  session.defaultSession.on('will-download', (_event, item) => {
      const fileName = item.getFilename();
      const ext = fileName.split('.')[fileName.split('.').length - 1];
      let fileType = 'Pluto Statefile';
      if (ext.endsWith('html')) fileType = 'HTML file';
      else if (ext.endsWith('jl')) fileType = 'Pluto Notebook';

      item.setSaveDialogOptions({
        message: 'Select location to export file',
        filters: [{ extensions: [ext], name: fileType }],
      });
  });

  createRequestListener();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', async () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// WHAT EXACTLY DOES THIS DO?
app.on('will-quit', () => {
      Pluto.close();
});

app.on('open-file', async (_event, file) => {
  // TODO: Implement filesystem open
  _event.preventDefault();
  console.log(file);
  console.log(app.isReady());
  console.log(GlobalWindowManager.getInstance().plutoWindows.length);
  // await createWindow(file);
});

// This handles custom Pluto.jl routes by intercepting web requests
function createRequestListener() {
  session.defaultSession.webRequest.onBeforeRequest(async (details, next) => {
    let cancel = false;

    if (!details.webContentsId) {
      generalLogger.warn('Web request was made without defined webContentsId');
      next({ cancel });
      return;
    }

    const plutoWindow =
      GlobalWindowManager.getInstance().getWindowByWebContentsId(
        details.webContentsId,
      );

    if (!plutoWindow) {
      next({ cancel });
      return;
    }

    // In development, our path usually looks like /.../Pluto.jl/frontend
    // In production, our path usually looks like  /.../Pluto/KkVLI/frontend
    if (details.url.match(/\/Pluto(\.jl)?\/(.*\/)?frontend(-dist)?/g)) {
      const url = new URL(details.url);
      const tail = url.pathname.split('/').reverse()[0];

      generalLogger.verbose(
        'Triggered Pluto.jl server-side route detection!',
        details.url,
      );

      if (url.pathname.endsWith('/')) {
        next({ redirectURL: Pluto.resolveHtmlPath('index.html') });
        return;
      }
      if (tail === 'new') {
        // this should be synchronous so the user sees the Pluto.jl loading screen on index.html
        await plutoWindow.open('new');
        next({
          cancel: true,
        });
        return;
      }
      if (tail === 'open') {
        await plutoWindow.open('path', url.searchParams.get('path'));
        next({
          cancel: true,
        });
        return;
      }
      if (tail === 'edit') {
        next({
          redirectURL:
            Pluto.resolveHtmlPath('editor.html') + url.search.replace('?', '&'),
        });
        return;
      }
      // this route gets called when pasting a notebook into the welcome page
      if (tail === 'notebookupload') {
        next({
          redirectURL: new URL(
            `notebookupload?secret=${Globals.PLUTO_SECRET}`,
            Globals.PLUTO_URL,
          ).toString(),
        });
      }
    }

    next({ cancel });
  });
}