/**
 * Main process of the Electron application.
 */
import { app, BrowserWindow, nativeTheme, session } from 'electron';
import * as path from 'path';
import { updateElectronApp, UpdateSourceType } from 'update-electron-app';
import Pluto from './pluto';
import './baseEventListeners.ts';
import { initGlobals, startup } from './startup.ts';
import { generalLogger } from './logger.ts';
import { GlobalWindowManager } from './windowHelpers.ts';
import { Globals } from './globals.ts';
import { getAssetPath } from './paths.ts';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const AUTO_UPDATE_CHECK_DELAY_MS = 2 * 60 * 1000;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const scheduleAutoUpdateChecks = () => {
  // Check for new releases on GitHub (via update.electronjs.org), download them
  // in the background, and prompt the user to restart. No-op during development.
  setTimeout(() => {
    updateElectronApp({
      updateSource: {
        type: UpdateSourceType.ElectronPublicUpdateService,
        repo: 'JuliaPluto/PlutoDesktop',
      },
      updateInterval: '1 hour',
      logger: generalLogger,
    });
  }, AUTO_UPDATE_CHECK_DELAY_MS);
};

/**
 * Create a new BrowserWindow and attach a Pluto instance to it.
 * Returns the Pluto instance. Exported so the menu can spawn new windows.
 */
export const createPlutoWindow = (landingUrl?: string | null): Pluto => {
  const win = new BrowserWindow({
    title: 'Pluto.jl',
    height: 800,
    width: 700,
    resizable: true,
    show: true,
    backgroundColor: nativeTheme.shouldUseDarkColors ? '#1F1F1F' : 'white',
    icon: getAssetPath('icon.png'),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      sandbox: false,
    },
  });

  const defaultLandingUrl = Globals.PLUTO_STARTED
    ? Pluto.resolveHtmlPath('index.html')
    : MAIN_WINDOW_WEBPACK_ENTRY;
  const pluto = new Pluto(
    win,
    landingUrl === undefined ? defaultLandingUrl : landingUrl,
  );
  win.focus();

  win.webContents.setVisualZoomLevelLimits(1, 3);
  win.setMenuBarVisibility(false);

  return pluto;
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(async () => {
  // Show the loading window right away: initGlobals can take a while on first
  // run (it copies the bundled Julia depot to a writable location).
  createPlutoWindow();
  await initGlobals();
  startup(app, MAIN_WINDOW_WEBPACK_ENTRY, scheduleAutoUpdateChecks);

  // This is set here because it required the app to be ready
  session.defaultSession.on('will-download', (_event, item) => {
    const fileName = item.getFilename();
    const ext = path.extname(fileName).slice(1);
    const fileType =
      ext === 'html'
        ? 'HTML file'
        : ext === 'jl'
          ? 'Pluto Notebook'
          : 'Pluto Statefile';

    item.setSaveDialogOptions({
      message: 'Select location to export file',
      filters: [{ extensions: [ext], name: fileType }],
    });
  });

  createRequestListener();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', async () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createPlutoWindow();
  }
});

// Kill the Julia/Pluto server process when the app quits.
app.on('will-quit', () => {
  Pluto.close();
});

app.on('open-file', (event, file) => {
  // TODO: open the file in a window (macOS "Open With" support).
  event.preventDefault();
  generalLogger.info('open-file event received (not implemented):', file);
});

// This handles custom Pluto.jl routes by intercepting web requests
function createRequestListener() {
  session.defaultSession.webRequest.onBeforeRequest(async (details, next) => {
    const cancel = false;

    if (!details.webContentsId) {
      generalLogger.warn('Web request was made without defined webContentsId');
      next({ cancel });
      return;
    }

    const plutoWindow =
      GlobalWindowManager.getInstance().getWindowByWebContentsId(
        details.webContentsId,
      );

    if (!plutoWindow) {
      next({ cancel });
      return;
    }

    // In development, our path usually looks like /.../Pluto.jl/frontend
    // In production, our path usually looks like  /.../Pluto/KkVLI/frontend
    if (details.url.match(/\/Pluto(\.jl)?\/(.*\/)?frontend(-dist)?/g)) {
      const url = new URL(details.url);
      const tail = url.pathname.split('/').reverse()[0];

      generalLogger.verbose(
        'Triggered Pluto.jl server-side route detection!',
        details.url,
      );

      if (url.pathname.endsWith('/')) {
        next({ redirectURL: Pluto.resolveHtmlPath('index.html') });
        return;
      }
      if (tail === 'new') {
        // this should be synchronous so the user sees the Pluto.jl loading screen on index.html
        await plutoWindow.open('new');
        next({
          cancel: true,
        });
        return;
      }
      if (tail === 'open') {
        await plutoWindow.open('path', url.searchParams.get('path'));
        next({
          cancel: true,
        });
        return;
      }
      if (tail === 'edit') {
        next({
          redirectURL:
            Pluto.resolveHtmlPath('editor.html') + url.search.replace('?', '&'),
        });
        return;
      }
      // this route gets called when pasting a notebook into the welcome page
      if (tail === 'notebookupload') {
        next({
          redirectURL: new URL(
            `notebookupload?secret=${Globals.PLUTO_SECRET}`,
            Globals.PLUTO_URL,
          ).toString(),
        });
        return;
      }
    }

    next({ cancel });
  });
}
